language: cpp
os:
  - osx
  - linux

addons:
  homebrew:
    update: true
    brewfile: true
  apt:
    packages:
      - libcppunit-dev
      - valgrind
      - r-base-core
      - lcov
      - python-pip
      - doxygen
      - graphviz

compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install --user cpp-coveralls cpplint; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then apt-cache policy zlib*; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then .ci/style.sh; fi

before_script:
  - ./bootstrap

script:
  - make
  - make check
  - if [ $TRAVIS_OS_NAME == linux ]; then ./tests/test_binary.sh; fi
  - ./tests/testPOS.sh
  - ./tests/test_binaryVcfVsTxt.sh
  - ./tests/test-against-previous-version.sh
  - ./tests/test_binaryReproducible.sh
  - if [ $TRAVIS_OS_NAME == linux ]; then cd docs/doxygen; doxygen Doxyfile; cd ../..; fi
  - rm -r *
  - wget --no-check-certificate https://github.com/DEploid-dev/DEploid/archive/master.tar.gz -o /dev/null
  - tar -xf master.tar.gz
  - cd DEploid-master
  - ./bootstrap
  - make; make check
  - cd ..; rm -r *
  - wget --no-check-certificate https://github.com/DEploid-dev/DEploid/archive/master.tar.gz -o /dev/null
  - tar -xf master.tar.gz
  - mv DEploid-master/* .
  - ./bootstrap
  - make; make check
after_success:
  - coveralls --exclude lib --exclude tests --exclude src/random --exclude src/codeCogs/ --exclude src/export/ --exclude src/gzstream/ --gcov-options '\-lp'
